baseurl: localhost
title: My Blog
language: en
theme: hello-4s3ti
paginate: 10

author:
  name: MakingDevs

copyright: "All rights reserved"

blackfriday:
  hrefTargetBlank: true

taxonomies:
  tag: tags
  category: categories

permalinks:
  posts: "posts/:year/:month/:day/:title/"
params:
  # Day formats
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"

  enableSharingButtons: true
  # metadata description
  description: "Nice theme for homepages and blogs"
  keywords: ""
  # home page
  homeTitle: "ViveCodigo.org"
  homeSubtitle: "EL PODCAST PARA DESARROLLADORES DE SOFTWARE."
  # backgroundImage @ home
  backgroundImage: "imagesa/bg_wall.png"
  backgroundEffects: true
  # theme dark/light
  enableThemeToggle: true
  # home posts
  showPosts: true
  # hideReadMore: true
  # showReadingTime: false

  ## footer
  footer:
    trademark: true
    copyright: true
    author: true

  logo:
    logoMark: ">"
    logoText: "$vive-codigo"
    logoHomeLink: "/"
    logoCursorColor: "#67a2c9"
    logoCursorAnimate: "6s"
menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts
    - identifier: about
      name: About
      url: /about
